---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name metrics-server
  namespace: kube-system
spec:
  releaseName: *name
  chart:
    spec:
      chart: *name
      version: "3.12.1"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
