apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name csi-secrets-store
  namespace: kube-system
spec:
  releaseName: *name
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "1.4.4"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true