apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &name secrets-provider-aws
  namespace: kube-system
spec:
  releaseName: *name
  chart:
    spec:
      chart: secrets-store-csi-driver-provider-aws
      version: "0.3.9"
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver-provider-aws
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3