apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver-provider-aws
  namespace: flux-system
spec:
  interval: 1h
  url: https://aws.github.io/secrets-store-csi-driver-provider-aws
