---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name aws-load-balancer-controller
  namespace: utilities
spec:
  releaseName: *name
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.8.1"
      sourceRef:
        kind: HelmRepository
        name: eks-charts
        namespace: flux-system
  interval: 50m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: alb-helm-values
  values:
    nodeSelector:
      tf-node-group: default-ng
    serviceAccount:
      create: true
