apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    CLUSTER_NAME: ENC[AES256_GCM,data:oXvU6/V3lyMPUEANpbk/VcI=,iv:DICsxPsTIqfw+QsUa7dCp7+xFrv/Hq4O/VRBeKJAgT4=,tag:mQ3mGHlRHqq3i+XyBMNkYA==,type:str]
    REGION: ENC[AES256_GCM,data:XopQB8uq9xDTVto9,iv:Jf2/zvOrIPF8wEXt0nUlq8dMxEF/ORtlGJVYgUPRDiQ=,tag:6Mgdb3p2ATFhL2R34L8Rew==,type:str]
    VPC_ID: ENC[AES256_GCM,data:8T/mFr/GBrO151gJKeuMWYsG2wwO,iv:FjXULcJU5w83VS/GFFDeJu2m0XEopryGAhCfYHU/BdI=,tag:Q10sKi6oYlZKtcyGKmcFSQ==,type:str]
    PUBLIC_SUBNETS: ENC[AES256_GCM,data:L3SOJyTWlgoFFnqpT0nkqV14c59TkBY6H0SC3sEn8Yt7KMXE3PxbE/EYQLt3be8LMl6no2F1FvsLQM6W,iv:84qgwZuIwjVBhV5etxngKzc2Fa9vkSdjt8r8plscMu0=,tag:SJEGo1vUrYhNF+qceOpjnA==,type:str]
    ALB_ROLE: ENC[AES256_GCM,data:JY/Olmzzw8uBWP4Suppl8emAClh6Bg2kd//3Sc0RJv4w9AWQVfDBOemPn7bAC1f9jXZmFwKFcFVHw6Y=,iv:bRF67UBie/nj6wd4OfOVm587ms3ZX2IFy0arm5bBkSk=,tag:NbDiyb/uh0ml0DbSe+QMdA==,type:str]
    DNS_ZONE: ENC[AES256_GCM,data:cImSJRVHF7JaHm2768NE3u3okQPMyVDO7hCjr0YJWu8XW3Oopw==,iv:nCCs2lArCBP1204TUNn9vr6smvSWA8kwGnDao7+xx1k=,tag:Pq3HcfsOT8ibu+4fWB4g7g==,type:str]
    DNS_ROLE: ENC[AES256_GCM,data:Vp4T3/MXkb4ICzMFo4aLDTs2f+3D4F/gzO+WF03XgVCxra4VNJxBo1npml7BRg5EYlBJBR6ed8n8,iv:zqvYUI/tVzeXwHXRsLJIX2v3syFvSv5pnUhe1rqufpE=,tag:4ar7NoP0x4nT5BkZfIxrOA==,type:str]
    ACM_ARN: ENC[AES256_GCM,data:kDm4ZiiJ38UdMwC0YbbOqJ9BElS4+v132zq1Ba4Nnh9rPJ4CRWYUeLdbqKNg9gk2RnB1cneCnkXvpOtf8nQieSDNgd8aLYJcDGhW9FdZmyIfj6kMpN8=,iv:rkvdRP4qsl/KxDl18hoH20IhirTlG52BELS7zacTwy8=,tag:ZCWsYMXYiO6WbYuvb6m1dg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18npnmueg5rplkxv6gvauz6qkjs3kukxhuuk4ugnlkkpu39k4zgqq7u2vde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTTdEbUNWYXllRVR1aGh4
            YS95N29MU1RQVm1adWYrZEhKdXNob0N4ZkZJCkFOSmZ4TXM4dGp0TG5qUWlyUThE
            LzNSNTJ3NVh1a1dpTlROc2Vwem9ackUKLS0tIGltTCtBVDRSRGJhK0Y3V2ZUVWZa
            elBVWTluUXcyZnBsVFZValJLZUhzTGcKrZaRTrq5aEq6tcaHfghzR9XJsI6e5RR8
            b7wyYQHNu3GS1Mq37jp+jjl4Ehxc2vXbEl/YOZFDJSr8SCRBW3B+ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T12:53:03Z"
    mac: ENC[AES256_GCM,data:b0drJBKAlQZdNyuTO6zKRhXDMX3DTeKRad8SMtTYwStY2OdoyZBsQmateOyb5SQphb1rgiEqcQKNYBf8uDUuPXn09X+/7uVayhyA8f39nWvbp5cDGS1EdtNUbsWPX7YdJQTSF/p25EvojuUt58SLh7fP78noDzSr9DOvbkv5LJA=,iv:8XCFRJQhPJkb5aviZeAV7xfVFghw6SNTxf7TwQYPul4=,tag:lE+GWchTSTKGDRJIrvlHPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
